### ISSUE TITLE
Editor version is out of date with respect to production

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo4unity#4]
There are a couple of issues with the current master,

- The model ids do not match any under the teamspace
- The asset bundles will not load in 2019.3.12f1 (which is the version in ProjectVersion.txt)

These the version and uuid simply need to be updated.

**Comment by mosment3DRepo** [comment]
@sebjf @carmenfan can this be closed?

**Comment by carmenfan** [comment]
@carmenfan Sebastian made a PR for this, I just forgot to look into it. We should merge it in and tag a new release. 

Leave it open and i'll sort it out.
